In [1]:
import pandas as pd
import numpy as np
from collections import Counter
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [2]:
# load the CSV file into a Pandas DataFrame
df = pd.read_csv("data.csv")

In [3]:
# extract features
elements = set([el for row in df['element_symbols'].str.split(',') for el in row])
data = []
for i, row in df.iterrows():
    element_counts = Counter(row['element_symbols'])
    feature = [element_counts[el] / row['nsites'] for el in elements]
    feature.extend([1 if el in row['element_symbols'] else 0 for el in elements])
    data.append(feature)

In [4]:
X = np.array(data)
y = df['spacegroup_num'].values

In [5]:
X.shape

(10628, 472)

In [6]:
print(X[:5])

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [7]:
# split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [8]:
# Train the random forest classifier
rfc = RandomForestClassifier(n_estimators=100, random_state=42)
rfc.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [12]:
# Make predictions on the test set
y_pred = rfc.predict(X_test)

In [13]:
# Calculate the accuracy of the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.14487300094073377
